package ru.skorobogatov.t_investsendbox.domain.entity

enum class InstrumentType(name: String) {

    INSTRUMENT_TYPE_BOND(name = "INSTRUMENT_TYPE_BOND"),
    INSTRUMENT_TYPE_SHARE(name = "INSTRUMENT_TYPE_SHARE"),
    INSTRUMENT_TYPE_CURRENCY(name = "INSTRUMENT_TYPE_CURRENCY"),
    INSTRUMENT_TYPE_ETF(name = "INSTRUMENT_TYPE_ETF"),
    INSTRUMENT_TYPE_FUTURES(name = "INSTRUMENT_TYPE_FUTURES"),
    INSTRUMENT_TYPE_SP(name = "INSTRUMENT_TYPE_SP"),
    INSTRUMENT_TYPE_OPTION(name = "INSTRUMENT_TYPE_OPTION"),
    INSTRUMENT_TYPE_CLEARING_CERTIFICATE(name = "INSTRUMENT_TYPE_CLEARING_CERTIFICATE"),
    INSTRUMENT_TYPE_INDEX(name = "INSTRUMENT_TYPE_INDEX"),
    INSTRUMENT_TYPE_COMMODITY(name = "INSTRUMENT_TYPE_COMMODITY"),
}