package ru.skorobogatov.t_investsendbox.domain.entity

enum class Timeframe(name: String) {

    CANDLE_INTERVAL_UNSPECIFIED(name = "CANDLE_INTERVAL_UNSPECIFIED"),
    CANDLE_INTERVAL_1_MIN(name = "CANDLE_INTERVAL_1_MIN"),
    CANDLE_INTERVAL_2_MIN(name = "CANDLE_INTERVAL_2_MIN"),
    CANDLE_INTERVAL_3_MIN(name = "CANDLE_INTERVAL_3_MIN"),
    CANDLE_INTERVAL_5_MIN(name = "CANDLE_INTERVAL_5_MIN"),
    CANDLE_INTERVAL_15_MIN(name = "CANDLE_INTERVAL_15_MIN"),
    CANDLE_INTERVAL_10_MIN(name = "CANDLE_INTERVAL_10_MIN"),
    CANDLE_INTERVAL_30_MIN(name = "CANDLE_INTERVAL_30_MIN"),
    CANDLE_INTERVAL_HOUR(name = "CANDLE_INTERVAL_HOUR"),
    CANDLE_INTERVAL_2_HOUR(name = "CANDLE_INTERVAL_2_HOUR"),
    CANDLE_INTERVAL_4_HOUR(name = "CANDLE_INTERVAL_4_HOUR"),
    CANDLE_INTERVAL_DAY(name = "CANDLE_INTERVAL_DAY"),
    CANDLE_INTERVAL_WEEK(name = "CANDLE_INTERVAL_WEEK"),
    CANDLE_INTERVAL_MONTH(name = "CANDLE_INTERVAL_MONTH")
}